apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-server-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-server
spec:
  hosts:
  - "*"
  gateways:
  - test-server-gateway
  http:
  - match:
    - uri:
        exact: /echo
    - uri:
        exact: /health
    - uri:
        prefix: /live
    - uri:
        prefix: /call
    route:
    - destination:
        host: test-server
        port:
          number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-server
  labels:
    app: test-server
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: test-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-server
  labels:
    app: test-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
      - name: test-server
        image: zackbutcher/test-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        args:
        - --server-port=80
        - --health-port=80
        - --liveness-port=80
        - --healthy=true
        - --liveness-delay=0s
        livenessProbe:
          httpGet:
            path: /live
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
