name: build-test
on: push

jobs:
  test:
    services:
      consul:
        image: consul:1.9.4
        ports:
          - 8500:8500
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: download dependencies
        run: go mod download

      - name: run tests
        run: go test -v -race ./...
